version: '3.1'
services:
  stats-server:
    build: ./statistic/statistic-server
    container_name: statistic-service-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=statistics
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - DB_HOST=stats-db #имя описания контейнера (так же как и в depends_on)
      - DB_PORT=5432
  #      - TZ=Europe/Moscow

  stats-db:
    image: postgres:14-alpine
    container_name: db-statistics-container
    ports:
      - "6541:5432"
    # volume и связанная с ним директория в контейнере
    volumes:
      - /var/lib/postgresql/data/
    # переменные окружения
    environment:
      - POSTGRES_DB=statistics
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
  #      - TZ=Europe/Moscow

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
